"use client";
import { useEffect,useState } from 'react';
import { LockKeyhole,Unlock,FileText,Download,BookOpen } from 'lucide-react';
import type {Original} from './vault-types';
export default function Vault({password,onUnlock,onLock}:{password:string;onUnlock:(value:string)=>void;onLock:()=>void}){
 const [initialized,setInitialized]=useState<boolean|null>(null),[entry,setEntry]=useState<Original|null>(null),[records,setRecords]=useState<Original[]>([]),[input,setInput]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/vault?status=1').then(async r=>{if(!r.ok)throw Error();const d=await r.json() as {initialized:boolean};setInitialized(d.initialized);}).catch(()=>setError('請先登入網站，才能開啟原文區。'));},[]);
 useEffect(()=>{if(password)load(password).catch(e=>setError(e.message));else{setRecords([]);setEntry(null);}},[password]);
 async function load(pass:string,id=''){const r=await fetch('/api/vault'+(id?'?id='+id:''),{headers:{'X-Vault-Password':pass}});const data=await r.json() as Original[] & {error?:string};if(!r.ok)throw Error(data.error||'原文無法載入。');if(id)setEntry(data.find(x=>x.id===id)||null);else setRecords(data);}
 async function submit(){setBusy(true);setError('');try{if(!initialized){if(input.length<10)throw Error('密碼至少需要 10 個字元。');if(input!==confirm)throw Error('兩次輸入的密碼不一致。');const r=await fetch('/api/vault',{method:'POST',headers:{'X-Vault-Password':input}});if(!r.ok){const d=await r.json() as {error:string};throw Error(d.error);}setInitialized(true);}await load(input);onUnlock(input);setInput('');setConfirm('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function download(){if(!entry)return;const url=URL.createObjectURL(new Blob(['\ufeff'+entry.title+'\n來源：'+entry.source+'\n\n'+entry.text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=entry.title+'.txt';a.click();URL.revokeObjectURL(url);}
 return <main className="content vault"><div className="page-heading"><div><div className="eyebrow">PRIVATE ORIGINALS</div><h1>原文加密區</h1><p>收藏每一篇原文照片與文字，只在解鎖後閱讀。</p></div>{password&&<button className="secondary" onClick={onLock}><LockKeyhole size={17}/>鎖定原文區</button>}</div>{!password?<section className="vault-gate"><div className="vault-lock"><LockKeyhole size={32}/></div><h2>{initialized===false?'設定你的原文區密碼':'解鎖原文收藏'}</h2><p>{initialized===false?'設定後，8 月與 9 月兩篇文章的原始照片與完整文字會一併加密收藏。':'輸入獨立密碼，查看原始照片與文字檔。'}</p><label className="field">{initialized===false?'新密碼（至少 10 個字元）':'原文區密碼'}<input type="password" autoComplete={initialized?'current-password':'new-password'} value={input} onChange={e=>setInput(e.target.value)}/></label>{initialized===false&&<label className="field">再次輸入密碼<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}<button className="primary" disabled={busy||initialized===null} onClick={submit}><Unlock size={17}/>{busy?'正在處理…':initialized===false?'設定密碼並收藏範例':'解鎖原文區'}</button><p className="field-note">請妥善保管密碼，遺失後無法還原原文。重新整理頁面會自動鎖定。</p>{error&&<p role="alert" className="error">{error}{error.includes("登入")&&<a className="text-button" href="/signin-with-chatgpt?return_to=/" target="_top"> 登入網站</a>}</p>}</section>:<><div className="vault-open-note"><Unlock size={16}/>原文區已解鎖，本次可上傳並加密收藏新文章。</div><div className="vault-layout"><div className="vault-list">{records.map(r=><button key={r.id} className={entry?.id===r.id?'active':''} onClick={()=>load(password,r.id).catch(e=>setError(e.message))}><BookOpen size={20}/><div><strong>{r.title}</strong><small>{r.source}</small></div></button>)}</div><section className="vault-document">{entry?<><div className="exercise-heading"><div><h2>{entry.title}</h2><p>{entry.source}</p></div><button className="secondary" onClick={download}><Download size={16}/>下載文字檔</button></div><details open><summary>原始照片 · {entry.files.filter(f=>f.type.startsWith('image/')).length} 張</summary><div className="vault-photos">{entry.files.filter(f=>f.type.startsWith('image/')).map((f,i)=><a key={i} download={f.name} href={f.data}><img src={f.data} alt={entry.title+' 原文照片 '+(i+1)}/><span>第 {i+1} 張 · 點擊下載</span></a>)}</div></details><h3><FileText size={18}/>原文文字</h3><p className="transcription-note">依照片轉錄；少數文字若因拍攝角度不清楚，請對照照片。</p><div className="original-text">{entry.text}</div></>:<div className="vault-empty"><BookOpen size={32}/><p>點選一篇文章，查看照片與文字。</p></div>}{error&&<p className="error" role="alert">{error}</p>}</section></div></>}</main>
}

