import {useEffect,useState} from 'react';
import {read,write,derive,encrypt,decrypt,b64,download,type Envelope} from './storage';
import type {Original} from '../app/vault-types';
type Store={salt:string;verifier:Envelope;entries:Envelope};
export default function LocalVault(){
 const [store,setStore]=useState<Store>(),[loaded,setLoaded]=useState(false),[key,setKey]=useState<CryptoKey>(),[records,setRecords]=useState<Original[]>([]),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[title,setTitle]=useState(''),[source,setSource]=useState(''),[text,setText]=useState(''),[files,setFiles]=useState<File[]>([]);
 useEffect(()=>{read<Store>('vault').then(s=>{setStore(s);setLoaded(true);}).catch(()=>setError('無法使用裝置儲存空間。'));},[]);
 async function unlock(){setBusy(true);setError('');try{let s=store;if(!s){if(password.length<10||password!==confirm)throw Error('密碼至少 10 字元，兩次輸入須相同。');const salt=b64(crypto.getRandomValues(new Uint8Array(16))),k=await derive(password,salt);s={salt,verifier:await encrypt(k,'wadoche-v1'),entries:await encrypt(k,[])};await write('vault',s);setStore(s);}const k=await derive(password,s.salt);if(await decrypt(k,s.verifier)!=='wadoche-v1')throw Error();setRecords(await decrypt(k,s.entries));setKey(k);setPassword('');setConfirm('');}catch{setError(store?'密碼不正確或資料損壞。':'密碼至少 10 字元，兩次輸入須相同。');}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{if(!key||!store||!title.trim()||!source.trim()||!text.trim())throw Error('請填寫文章名稱、來源及原文文字。');if(files.reduce((n,f)=>n+f.size,0)>12*1024*1024||files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)))throw Error('只接受 JPG、PNG、WEBP，合計最多 12 MB。');const photos=await Promise.all(files.map(f=>new Promise<{name:string;type:string;data:string}>((res,rej)=>{const r=new FileReader();r.onload=()=>res({name:f.name,type:f.type,data:String(r.result)});r.onerror=()=>rej(Error('讀取失敗'));r.readAsDataURL(f);})));const next=[...records,{id:crypto.randomUUID(),title,source,text,files:photos}];const s={...store,entries:await encrypt(key,next)};await write('vault',s);setStore(s);setRecords(next);setTitle('');setSource('');setText('');setFiles([]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function restore(f?:File){if(!f)return;try{if(store)throw Error('這台裝置已有原文庫，請先備份；復原請使用尚未設定原文庫的瀏覽器。');const s=JSON.parse(await f.text());if(!s.salt||!s.verifier?.iv||!s.entries?.data)throw Error('備份格式不正確。');await write('vault',s);setStore(s);}catch(e){setError((e as Error).message);}}
 return <><div className="page-heading"><div><h1>原文加密區</h1><p>照片與文字加密保存於這台裝置。請下載備份，清除瀏覽器資料會失去收藏。</p></div>{key&&<button className="secondary" onClick={()=>{setKey(undefined);setRecords([]);}}>鎖定</button>}</div>{!key?<section className="panel"><h2>{store?'解鎖原文庫':'設定獨立密碼'}</h2><label className="field">密碼<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{!store&&<label className="field">再次輸入密碼<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}<button className="primary" disabled={!loaded||busy} onClick={unlock}>解鎖原文區</button>{!store&&<label className="field">或復原加密備份<input type="file" accept=".json" onChange={e=>restore(e.target.files?.[0])}/></label>}</section>:<><button className="secondary" onClick={()=>download('挖讀冊-加密原文備份.json',JSON.stringify(store))}>下載加密備份</button><section className="panel"><h2>收藏另一篇原文</h2><label className="field">文章名稱<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field">來源與期別<input value={source} onChange={e=>setSource(e.target.value)}/></label><label className="field">原文照片<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label><label className="field">完整原文文字<textarea value={text} onChange={e=>setText(e.target.value)}/></label><button className="primary" disabled={busy} onClick={save}>加密收藏</button></section>{records.map(r=><details className="panel" key={r.id}><summary>{r.title} · {r.source}</summary><button className="secondary" onClick={()=>download(r.title+'.txt',r.text,'text/plain;charset=utf-8')}>下載文字檔</button><div className="vault-photos">{r.files.map((f,i)=><a key={i} href={f.data} download={f.name}><img src={f.data} alt={r.title+'原文照片'+(i+1)}/></a>)}</div><div className="original-text">{r.text}</div></details>)}</>}{error&&<p role="alert" className="error">{error}</p>}</>;
}
